### ISSUE TITLE
Feature request emulator support

### ISSUE THREAD

**Issue by ZombiePelican007** [skyline-dev/skyline#46]
When do you guys think you could work that in specifically support for yuzu

**Comment by Raytwo** [comment]
Never. It is not up to us to implement the missing parts of Yuzu for Skyline to run.
This is designated with consoles in mind, and emulation is just not far enough yet for it to work, so you'll have to be patient.
Some work is being done on Ryujinx to run it though.

**Comment by ZombiePelican007** [comment]
No yeah I realized like two minutes after I sent this sorry for that lol

**Comment by jam1garner** [comment]
@ZombiePelican007 any progress on this front will likely be happening in the yuzu repo's issue instead: https://github.com/yuzu-emu/yuzu/issues/6076
