### ISSUE TITLE
[Bug] Skyline Prevents Game Launch

### ISSUE THREAD

**Issue by ThisNekoGuy** [skyline-dev/skyline#49]
Using **ARCopolis 2.1.0**, **Atmosphere 1.2.1**, on **firmware 13.1.0** with the [Skyline beta](https://github.com/skyline-dev/skyline/releases/tag/beta) prevents Smash Ultimate from loading :/

**Comment by imizaac** [comment]
I am also encountering this. Atmosphere 1.2.4, 13.1 firmware, latest build.

Where is the previous build?

**Comment by ThisNekoGuy** [comment]
I found that, personally, the reason was because I used FTP to put it on my Switch; re-doing it manually made it start up again normally but I have no idea why this is the case because it shouldn't have made a difference :/

**Comment by The1UPKing** [comment]
> I found that, personally, the reason was because I used FTP to put it on my Switch; re-doing it manually made it start up again normally but I have no idea why this is the case because it shouldn't have made a difference :/

Even when i manually updated arcropolis and skyline, it crashes on startup. It'll show to update pop up then after a couple minutes it just says "software aborting"

**Comment by MetalNeo** [comment]
> I found that, personally, the reason was because I used FTP to put it on my Switch; re-doing it manually made it start up again normally but I have no idea why this is the case because it shouldn't have made a difference :/

Manually adding the files did resolve the initial crash I was having, but I am still having issues getting mods to load.

**Comment by RSLKirby** [comment]
Everytime i launch smash ultimate,it says an error occurred. One of the mods i listed said to delete the exefs folder so i did so and ultimate launched but no mods were launched/working.

**Comment by Raytwo** [comment]
Guys, this is not the [ARCropolis](www.arcropolis.com) repository, please move there.
