### ISSUE TITLE
Skyline instantly crashes Smash Ultimate

### ISSUE THREAD

**Issue by fartzgaming** [skyline-dev/skyline#56]
I just installed Arcropolis and Skyline (latest versions, no mods added) and I can't launch Smash without either holding the L button or getting rid of the exefs folder (both ways make it so that Arcropolis doesn't load). When I do it normally it just says "Unable to start software. Return to the HOME Menu and try again." How do I fix this?

**Comment by shadowninja108** [comment]
The NPDM in the exefs folder may be corrupt. Try manually copying it over with hekate UMS or taking the SD card out.

**Comment by fartzgaming** [comment]
> The NPDM in the exefs folder may be corrupt. Try manually copying it over with hekate UMS or taking the SD card out.

I did a little tinkering and it maybe subsdk9 is the culprit? After renaming the file it just loads Smash without Arcropolis.

**Comment by shadowninja108** [comment]
Could be that too. Either way, it sounds like corruption on your end.

**Comment by fartzgaming** [comment]
That sucks, all I did was download Skyline from the official github and transferred it to my switch via FTP. I don't wanna have to take out my SD and restart my switch every time I wanna transfer a file.

**Comment by shadowninja108** [comment]
Some FTP clients manager extension-less files incorrectly by default. See if you can somehow disable “text mode” or force enable “binary mode” in the settings somewhere. I don’t think this would be an issue with every file.

**Comment by fartzgaming** [comment]
Holy shit, all I had to do was uncheck "Treat files without extensions as ASCII file". Thank you so much.
