### ISSUE TITLE
Skyline Plugin has panicked for ARCropolis 3.1.1

### ISSUE THREAD

**Issue by YN0T1** [skyline-dev/skyline#57]
![Skyline error](https://user-images.githubusercontent.com/47356406/160292358-87f29a53-4667-4c41-afc3-0eea2eab165b.jpg)
![Skyline error 2](https://user-images.githubusercontent.com/47356406/160292379-e27cfd97-4596-45e1-bfa5-700bdd7d51d0.jpg)

**Comment by shadowninja108** [comment]
As it says, a skyline plugin panicked, not skyline. It sounds like one of your plugins is old/misbehaving.

**Comment by YN0T1** [comment]
Is there an easy way to tell which mod is causing this issue or do I just have to try random ones?

**Comment by shadowninja108** [comment]
Scientific method. Remove all your mods and add them back one by one and test if it works.
