### ISSUE TITLE
Skyline plugin has panicked

### ISSUE THREAD

**Issue by VongolaPrimoEdu** [skyline-dev/skyline#58]
After updating my switch yesterday, i tried to put the mods again. had an old atmosphere version and had to update to the latest, and in the process i deleted my old atmosphere folder. I reinstalled everything again and for a moment had everything working... except the training mod. this morning I tried again and managed to get everything right. But i quit my sd card one last time to check some conflicts with mods and fix them. This two errors happened
![error 1](https://user-images.githubusercontent.com/96431272/161999837-d29f8225-d00c-4c25-9835-699790333e60.jpg)
![error2](https://user-images.githubusercontent.com/96431272/162000004-e1b7da19-ff58-4d6d-98fa-c5aeb7a67127.jpg)
I´ve been fighting with my switch for almost 2 hours already. downloaded everything from 0 in a step by step guide, nothing worked lmao. I tried deleting the plugins file altogether and it obviously worked but smash started without mods. i dunno what causes it, i have the most recent version of both the training modpack and arcadia. Any ideas? i can provide more screenshots of my atmosphere folder if needed

**Comment by VongolaPrimoEdu** [comment]
apparently i´ve tried to literally restart smash ultimate multiples times and it managed to start? i have no idea how, but i refuse to replicate it, i spent way too much time on this lol. info would be helpful for next time tho

**Comment by shadowninja108** [comment]
The message says a skyline plugin panicked, not skyline itself. You’d want to seek help from a modding forum for this, this isn’t a bug on our end.
