### ISSUE TITLE
Explanation missing how to use Skyline

### ISSUE THREAD

**Issue by dustin2711** [skyline-dev/skyline#59]
Hello,
I cannot find any explanation on how to use Skyline, e.g. where to copy which files in order to use it. I think you should really add it to your github page!

**Comment by Raytwo** [comment]
Hey there,

I know this doesn't fix the core issue, but [here is a link](https://github.com/Raytwo/ARCropolis/issues/157) where I explain this for Smash Ultimate. Just make sure to change the titleid in the path for the game of your choosing!

**Comment by Raytwo** [comment]
[FTFY](https://github.com/skyline-dev/skyline#usage)
