### ISSUE TITLE
Skyline plugin has panicked

### ISSUE THREAD

**Issue by SignorUpB** [skyline-dev/skyline#61]
I have never had this problem before but today this showed up before opening smash,is there any way i can fix this?
![2022043019301500-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/104692273/166116681-67ebae67-09f6-43c1-b02c-e9270e3df317.jpg)
![exefs 30_04_2022 19_51_18](https://user-images.githubusercontent.com/104692273/166116775-f3bac133-88b9-434f-9032-2f61dcb5c78e.png)
![exefs 30_04_2022 19_50_47](https://user-images.githubusercontent.com/104692273/166116776-e4039b6a-4db6-4939-ad9e-7fa45d32e559.png)
![exefs 30_04_2022 19_51_01](https://user-images.githubusercontent.com/104692273/166116777-9800ae0c-bc33-4c29-9e6b-703be1da7975.png)

**Comment by shadowninja108** [comment]
As the message says, a skyline plugin panicked, not skyline. Narrow down which plugin is causing the issue. You also did everything but what the message said, show the details. Show that to the developer of whatever plugin is causing the issue.
