### ISSUE TITLE
eiffel isn't a directory 

### ISSUE THREAD

**Issue by jIdle** [skyline-dev/skyline#63]
https://github.com/skyline-dev/skyline/blob/f44b3fe9278069b01d12f0d31a353c7f7b281d82/include/skyline/efl/service.hpp#L3

This include doesn't reference a directory that exists. I'm running into this issue when running make.
 error: eiffel/sl.h: No such file or directory
    3 | #include "eiffel/sl.h"
      |          ^~~~~~~~~~~~~
compilation terminated.

**Comment by shadowninja108** [comment]
You've not initialized the submodules.
I believe you'd do:
```
git submodule init
git submodule update
```

**Comment by jIdle** [comment]
Awesome, that worked perfectly. Thank you.
