### ISSUE TITLE
Skyline has Panicked

### ISSUE THREAD

**Issue by ceorng** [skyline-dev/skyline#64]
For the past 2 days i've tested things, I've uninstalled mods, resetup my sd card, reformatted it. everything. This is the error
![unknown](https://user-images.githubusercontent.com/106507651/170922965-4e61e9cb-129f-44b2-87fc-13939917cd59.png)

what do I do???

**Comment by shadowninja108** [comment]
The message explicitly says, "A skyline *plugin* panicked". This is not a skyline issue. Given the exception message mentions a config library arcropolis uses, I'd guess your arcropolis config is corrupt. Try deleting /ultimate/arcropolis. Seek help on a smash modding discord if that doesn't help.
