### ISSUE TITLE
Skyline has panicked

### ISSUE THREAD

**Issue by SignorUpB** [skyline-dev/skyline#66]

**Comment by SignorUpB** [comment]
Yesterday i got this issue while opening smash
![2022072211155200-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/104692273/180407782-e10c7d25-ee72-4220-8612-b54c217c815e.jpg)

**Comment by shadowninja108** [comment]
It would say a skyline plugin has panicked, not skyline. This is a plugin problem, not skyline. Seek help from the community discord servers.
