### ISSUE TITLE
Error Code: 2--0069 [The game said to screenshot and send to developer]

### ISSUE THREAD

**Issue by VeoScool** [skyline-dev/skyline#67]
This error message popped up after the "system" told me to make a screenshot

I'm currently running hetake (5.7.0_Nyx_1.2.0) and atmosphere (1.3.1) with arcropolis (version unknown)

![2022080821034600-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/31881448/183494994-eef23876-320f-4455-978b-d47bdfc1d909.jpg)

**Comment by shadowninja108** [comment]
This isn’t a skyline issue. Join a modding discord and seek troubleshooting help.
