### ISSUE TITLE
Skyline error after enabling mods

### ISSUE THREAD

**Issue by Mlwxrk** [skyline-dev/skyline#68]
![error](https://user-images.githubusercontent.com/62304385/188249644-50a1c06f-1434-4972-81b2-d721276e10bc.jpeg)

After installing ARCropolis and enabling mods through the e-shop menu, I get the error message above when trying to launch smash bros. I tried manually putting the skyline files through FTP, but nothing seemed to work. Prompt suggests asking the dev.
Thanks

**Comment by shadowninja108** [comment]
This is a skyline plugin panicking, not skyline. If I was to guess, your arcropolis configuration is corrupt. You can delete `/ultimate/arcropolis` to reset it. If that doesn’t work, seek help in a smash modding discord.
