### ISSUE TITLE
Skiline paniked

### ISSUE THREAD

**Issue by Gaiafett** [skyline-dev/skyline#69]
![20221107_112921](https://user-images.githubusercontent.com/94815495/200381634-56e20686-0f7b-404b-881f-08f960a22813.jpg)
very good day I hope you can help me I don't know what to do yesterday early it worked fine since I was playing without any problem but at night I tried to add some new mods it stopped working and it gave me an error I deleted the mods that I installed I even put it back pluging and the exef and then it gave me that error how do I fix it thanks in advance hand

**Comment by shadowninja108** [comment]
This is not a skyline issue. Seek support in a Smash modding discord.
