### ISSUE TITLE
Error code- skyline panicked

### ISSUE THREAD

**Issue by Mkellez** [skyline-dev/skyline#72]
![2023012114444400-1AB131B6E6571375B79964211BB3F5AE](https://user-images.githubusercontent.com/123269348/213884806-ad93e0e6-d6cd-4f03-b546-41b749ea48c0.jpg)

I was going to select a stage in training mode and this error occurred. Just thought I'd inform you all.

**Comment by shadowninja108** [comment]
This error has nothing to do with skyline. Troubleshoot whatever plugin is causing it and seek support from the correct project.

**Comment by jugeeya** [comment]
@Mkellez FWIW, this is a training modpack issue. Please install the latest beta, where this issue is fixed.
