### ISSUE TITLE
[Feature Request] Ryujinx LDN support

### ISSUE THREAD

**Issue by KakarottoCake** [skyline-dev/skyline#73]
Skyline already works on Ryujinx, but all we need now is LDN support and then everything will be perfect. Please consider adding support for this

**Comment by shadowninja108** [comment]
You have things backwards, LDN is a service provided by the OS, and so by Ryujinx. It's Ryujinx's job to handle that. Skyline doesn't even know what LDN is.,,

**Comment by KakarottoCake** [comment]
The Ryujinx devs don't think so![](https://media.discordapp.net/attachments/919465019677220894/1066594981738987580/Screenshot_20230122_004703_Discord.jpg)

**Comment by shadowninja108** [comment]
They provided you the solution. Do that. It's Ryujinx improper socket handling that conflicts with what Skyline does, I believe. There may be developments that work around that, but ultimately, it's not *our* problem.
