### ISSUE TITLE
Skyline error

### ISSUE THREAD

**Issue by Mkellez** [skyline-dev/skyline#76]
Hello, I've been having an error code that I'm unfamiliar with. Does anyone think that they'll able to help me?
![29503C14-153B-44D4-B1B1-7BF3128775AC](https://user-images.githubusercontent.com/123269348/225066183-c5a64e79-aa66-4944-83ce-d8220fa9f8df.jpeg)

**Comment by shadowninja108** [comment]
This isn’t a skyline issue. I’d guess your arcropolis config is corrupt, try deleting /ultimate/arcropolis. If that doesn’t help, seek help on Discord or something.

**Comment by Mkellez** [comment]
Unfortunately that method didn't work. Do you have a link to the discord?
