### ISSUE TITLE
Skyline error

### ISSUE THREAD

**Issue by Mkellez** [skyline-dev/skyline#77]
I'm having an error when trying to load my mods. Someone recommended that I remove the acropolis file in ultimate/acropolis, which I did but the error still occurs. Is there any way that someone can help me resolve this issue?
![29503C14-153B-44D4-B1B1-7BF3128775AC](https://user-images.githubusercontent.com/123269348/225653593-70bae6f4-6386-4dfb-bf85-eb59e36fee46.jpeg)

**Comment by shadowninja108** [comment]
This is still not relevant to skyline. Please seek help from an actual forum. Issues is for bugs, not support.
