### ISSUE TITLE
Guide to making main.npdm?

### ISSUE THREAD

**Issue by RhanCandia** [skyline-dev/skyline#78]
I was trying to use [the p5rs](https://github.com/Raytwo/p5rcbt) but the game just crashes. Maybe the main.ndpm needs to be updated with the patched main.ndpm from the latest update of the game?

Is there any guide on how and what to patch on the main.ndpm file?

I tried looking it up but I can't find anything.

I'm not really making mods for Switch games. I just wanted to make the https://github.com/Raytwo/p5rcbt work.

**Comment by Raytwo** [comment]
Hello, it crashes because the code was made for version 1.0.0 and the lack of interest in it made me not update it.

**Comment by shadowninja108** [comment]
This is not a skyline issue. Please report issues to the correct repo. You can convert a NPDM to JSON with hactool and vice versa with npdmtool (provided in devkitA64). This however, as stated, will not help you as the NPDM isn’t the problem.
