### ISSUE TITLE
issue after trying to install one-slot-effects

### ISSUE THREAD

**Issue by Whorable1** [skyline-dev/skyline#81]
Hey there! I was prompted with "ARCropolis has panicked!" after trying to install one-slot-effects. I tried to fix this myself by deleting the files that I had added in my plugins, but to no avail. I assume this is where i should post my screenshot of my issue. Any help is greatly appreceated!

![IMG_3434](https://github.com/skyline-dev/skyline/assets/144571182/b76f6206-a19e-473c-8b5c-bca1c11811b6)

Error Code: 2-0069

**Comment by Whorable1** [comment]
I forgot to add, here is a link to the files I've added and then removed: https://drive.google.com/drive/folders/1Wg2TzZhc1LuMpW5P016Sz7Or0Ol3kJ8v?usp=sharing

Please let me know if the link doesn't work

**Comment by shadowninja108** [comment]
As it says, arcropolis panicked. This isn’t the arcropolis repository and GitHub isn’t really a support channel. Join a smash modding discord and ask for assistance. GitHub issues are for verifiable bugs.
